config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admins
  resources :users do
    resources :loans do
      resources :payments
    end
  end

  post '/users/:user_id/loans/:loan_id/payments/:id/pay' , to: 'payments#pay' , as: 'payments_pay'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :loans
	has_many :payments
	before_save :default_values

	private
	def default_values
		unless self.totalDebt 
			self.totalDebt = 0
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @loans = @user.loans
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstName, :lastName, :address, :phone, :dni, :totalDebt)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName, "Nombre" %>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName, "Apellidos" %>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :address, "Dirección" %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone, "Telefono" %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :dni, "DNI" %>
    <%= f.text_field :dni %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "button"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1>Editar Persona</h1>

	<%= render 'form' %>

	<%= link_to 'Mostrar', @person %> |
	<%= link_to 'Regresar', users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Prestatarios</h1>

  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellidos</th>
        <th>Dirección</th>
        <th>Teléfono</th>
        <th>Dni</th>
        <th>Deuda Total</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.firstName %></td>
          <td><%= user.lastName %></td>
          <td><%= user.address %></td>
          <td><%= user.phone %></td>
          <td><%= user.dni %></td>
          <td><%= user.totalDebt %></td>
          <td><%= link_to 'Mostrar', user %></td>
          <td><%= link_to 'Editar', edit_user_path(user) %></td>
          <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
          <td><%= link_to 'Prestar Dinero', new_user_loan_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Prestatario', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="row container">
	<h1>Nuevo Prestatario</h1>

	<%= render 'form' %>

	<%= link_to 'Regresar', users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="container-top">
  <h2>Prestamos de </h2>
  <h3> <%= @user.firstName %></h3>
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Apellidos:</strong>
    <%= @user.lastName %>
  </p>

  <p>
    <strong>Dirección:</strong>
    <%= @user.address %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= @user.phone %>
  </p>

  <p>
    <strong>Dni:</strong>
    <%= @user.dni %>
  </p>

  <p>
    <strong>Deuda Total:</strong>
    <%= @user.totalDebt %>
  </p>
</div>
<div class="loans">
  <h4 class="text-center"> Mis Prestamos :</h4>
  <table class="text-center">
    <thead>
      <tr>
        <th>Fecha de Desembolso</th>
        <th>Monto</th>
        <th>Interés diario</th>
        <th>Plazo (en días)</th>
        <th>Tipo de Amortización</th>
        <th>Detalle</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @loans.each do |loan| %>
        <tr>
          <td><%= loan.dateLoan %></td>
          <td><%= loan.amount %></td>
          <td><%= loan.dailyInterest %></td>
          <td><%= loan.term %></td>
          <td><%= loan.typeAmortization %></td>
          <td><%= loan.detail %></td>
          <td><%= link_to 'Mostrar Tabla de amortización',  user_loan_payments_path(@user,loan) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  
  <%= link_to 'Añadir Prestamos', new_user_loan_path(@user)%> |
  <%= link_to 'Regresar', users_path %>
  
</div>