config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admins
  resources :users do
    resources :loans do
      resources :payments
    end
  end

  post '/users/:user_id/loans/:loan_id/payments/:id/pay' , to: 'payments#pay' , as: 'payments_pay'

  root 'welcome#index'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :user
  has_many :payments
  before_save :add_mountUser

  private
  def add_mountUser
  	@usuario = self.user
  	@newDebt = @usuario.totalDebt + self.amount
  	@usuario.totalDebt = @newDebt
  	@usuario.save!
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  before_action :set_person
  before_action :authenticate_admin!
  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    @loan.user = @user
    respond_to do |format|
      if @loan.save
          format.html { redirect_to :controller => 'payments', :action => 'create' , :loan_id => @loan.id,  :method => 'post' }
          format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end
    def set_person
      @user = User.find(params[:user_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:people_id, :dateLoan, :amount, :dailyInterest, :term, :detail, :typeLoan, :typeAmortization)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for([@user,@loan]) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :dateLoan , "Fecha de Desembolso" %>
    <%= f.date_select :dateLoan %>
  </div>
  <div class="field">
    <%= f.label :amount , "Monto" %>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :typeLoan , "Periodo de Amortizacíón" %>
    <%= f.select :typeLoan , options_for_select([["Diario", "Diario"], ["Semanal", "Semanal"], ["Mensual","Mensual"]])  %>
  </div>
  <div class="field">
    <%= f.label :typeAmortization , "Periodo de Amortizacíón" %>
    <%= f.select :typeAmortization , options_for_select([["Cuotas Constantes", "Cuotas Constantes"]])  %>
  </div>
  <div class="field">
    <%= f.label :dailyInterest, "Interés Diario" %>
    <%= f.text_field :dailyInterest %>
  </div>
  <div class="field">
    <%= f.label :term ,"Plazo (en días)" %>
    <%= f.number_field :term %>
  </div>
  <div class="field">
    <%= f.label :detail, "Detalles" %>
    <%= f.text_area :detail , rows: "4"  %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" , class: "button" %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loan_people_path %>

app/views/loans/index.html.erb
<div class="container">  
  <p id="notice"><%= notice %></p>

  <h1>Prestamos</h1>

  <table>
    <thead>
      <tr>
        <th>Persona</th>
        <th>Fecha de Desembolso</th>
        <th>Monto</th>
        <th>Interés diario</th>
        <th>Plazo (en días)</th>
        <th>Detalle</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @loans.each do |loan| %>
        <tr>
          <td><%= loan.people %></td>
          <td><%= loan.dateLoan %></td>
          <td><%= loan.amount %></td>
          <td><%= loan.dailyInterest %></td>
          <td><%= loan.term %></td>
          <td><%= loan.detail %></td>
          <td><%= link_to 'Show', loan %></td>
          <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
          <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Prestamo', new_person_loan_path %>
</div>

app/views/loans/new.html.erb
<div class="container">
	<h1>Nuevo Préstamo</h1>

	<%= render 'form' %>
</div>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>People:</strong>
  <%= @loan.people %>
</p>

<p>
  <strong>Dateloan:</strong>
  <%= @loan.dateLoan %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @loan.amount %>
</p>

<p>
  <strong>Dailyinterest:</strong>
  <%= @loan.dailyInterest %>
</p>

<p>
  <strong>Term:</strong>
  <%= @loan.term %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @loan.detail %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loan_people_path %>