config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admins
  resources :users do
    resources :loans do
      resources :payments
    end
  end

  post '/users/:user_id/loans/:loan_id/payments/:id/pay' , to: 'payments#pay' , as: 'payments_pay'

  root 'welcome#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :loan
  before_save :default_values
  def default_values
		unless self.state 
			self.state = 0
		end
	end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy, :pay]
  before_action :set_person
  before_action :set_loan
  before_action :authenticate_admin!

  # GET /payments
  # GET /payments.json
  def index
    @payments = @loan.payments
    @quantity = @loan.payments.count
    @totalAmortization = @loan.payments.sum(:amortization).round(2)
    @totalInterest = @loan.payments.sum(:interest).round(2)
    @totalFee = @loan.payments.sum(:fee).round(2)

    respond_to do |format|
      format.html
      format.pdf do
        pdf = PaymentPdf.new(@loan, @totalAmortization , @totalInterest , @totalFee ) 
        send_data pdf.render, filename: "Pago_#{@loan.user.firstName}.pdf",
                              type: "aplication/pdf",
                              disposition: "inline"

      end
    end

  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  def pay
    if @payment.update(:state => 1)
        redirect_to user_loan_payments_path
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
  end
  # POST /payments
  # POST /payments.json
  def create
    @days = @loan.term
    @interest = @loan.dailyInterest/100
    @amount = @loan.amount
    @cuot = ((@interest * @amount) / (1 - ((1/(1+@interest)))**@days))
    @cuotRound = @cuot.round(2)
    @inicialBalance = @amount
    @datePay = @loan.dateLoan
    
    
    @days.times{
      @payment = Payment.new


      @interestAmount = (@inicialBalance * @interest) .round(2)
      @amortization = (@cuotRound - @interestAmount).round(2)
      @finalBalance = (@inicialBalance - @amortization).round(2)
      
      @payment.fee = @cuotRound
      @payment.inicialBalance = @inicialBalance
      @payment.interest = @interestAmount
      @payment.amortization = @amortization
      @payment.finalBalance = @finalBalance
      @payment.datePay = @datePay

      @payment.user = @user
      @payment.loan = @loan
      @payment.save

      @inicialBalance = @finalBalance
      @datePay = @datePay + 1
    }
    
    redirect_to user_loan_payments_path
    

  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end
    def set_loan
      @loan = Loan.find(params[:loan_id])
    end
    def set_person
      @user = User.find(params[:user_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      #params.require(:payment).permit(:user_id, :loan_id, :datePay, :inicialBalance, :amortization, :interest, :fee, :finalBalance)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :loan_id %><br>
    <%= f.text_field :loan_id %>
  </div>
  <div class="field">
    <%= f.label :datePay %><br>
    <%= f.date_select :datePay %>
  </div>
  <div class="field">
    <%= f.label :inicialBalance %><br>
    <%= f.text_field :inicialBalance %>
  </div>
  <div class="field">
    <%= f.label :amortization %><br>
    <%= f.text_field :amortization %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_field :fee %>
  </div>
  <div class="field">
    <%= f.label :finalBalance %><br>
    <%= f.text_field :finalBalance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Lista de Pagos</h1>

  <table>
    <thead>
      <tr>
        <th>Número</th>
        <th>Fecha de Pago</th>
        <th>Saldo inicial</th>
        <th>Amortización</th>
        <th>Intereres</th>
        <th>Cuota</th>
        <th>Saldo Final</th>
        <th>Acciones</th>
      </tr>
    </thead>

    <tbody>
    <% @number = 1 %>
      <% @payments.each do |payment| %>
        <tr>
          <td><%= @number %></td>      
          <td><%= payment.datePay %></td>
          <td>S/. <%= payment.inicialBalance %></td>
          <td>S/. <%= payment.amortization %></td>
          <td>S/. <%= payment.interest %></td>
          <td>S/. <%= payment.fee %></td>
          <td>S/. <%= payment.finalBalance %></td>
          <% if payment.state == 0 %> 
            <td><%= link_to "Pagar" , payments_pay_path(@user,@loan,payment) , method: :post  %></td>
          <% else %>
            <td><strong class="red text-center">Pagado</strong>
          <%end %>
        </tr>
        <% @number = @number + 1 %>
      <% end %>
      <td> <b>Total</b></td>
      <td> </td>
      <td></td>
      <td>S/. <%= @totalAmortization %></td>
      <td>S/. <%= @totalInterest %></td>
      <td>S/. <%= @totalFee %></td>
    </tbody>
  </table>
  <% if @quantity == 0 %>
    <%= button_to "Generar Amortizacion", { action: "create" } , class: "button"  %>
  <% else %>
    <%= link_to "Generar Documento" , user_loan_payments_path(format: "pdf"),  class: "button"  %>
  <% end %>


</div>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/pay.html.erb
pay.html.erb

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @payment.user %>
</p>

<p>
  <strong>Loan:</strong>
  <%= @payment.loan %>
</p>

<p>
  <strong>Datepay:</strong>
  <%= @payment.datePay %>
</p>

<p>
  <strong>Inicialbalance:</strong>
  <%= @payment.inicialBalance %>
</p>

<p>
  <strong>Amortization:</strong>
  <%= @payment.amortization %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @payment.interest %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @payment.fee %>
</p>

<p>
  <strong>Finalbalance:</strong>
  <%= @payment.finalBalance %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>